### ISSUE TITLE
Where is fullcalendar

### ISSUE THREAD

**Issue by larry-tx** [philippfrenzel/yii2fullcalendar-demo#1]
This "demo" doesn't seem to include anything but the original Yii2 basic template. Where can I find the fullcalendar demo implementation?

**Comment by philippfrenzel** [comment]
http://yii2fullcalendar.beeye.org/

should appear here;)

**Comment by philippfrenzel** [comment]
And here:

https://github.com/philippfrenzel/yii2fullcalendar-demo/blob/master/views/site/index.php
